# Generated by Django 5.0.3 on 2024-04-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teachid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
